### ISSUE TITLE
An unimplemented!() is reachable after all.

### ISSUE THREAD

**Issue by nbigaouette** [tokio-rs/tokio-line#8] opened 2016-08-30 02:35 UTC
I'm looking into `tokio-line` to see if I can adapt it to my use case.

I modified `framed_transport.rs`'s `parse()` method (of the `Parse` trait) to naively parse the kind of packet I'm working with. This protocol is binary and the packets are simply composed of a magic number, the packet size, and some data.

For now I concentrate on the client side. I have a dummy server simulator that waits for a series of specific bytes and replies with another series.

When trying this out I get a panic from the client:

```
thread '<unnamed>' panicked at 'not yet implemented', /Users/nicolas/.cargo/git/checkouts/tokio-proto-c8cedf07823756f8/master/src/proto/pipeline/pipeline.rs:143
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:788
error: Process didn't exit successfully: `target/debug/examples/client` (exit code: 101)
```

Since I am not entirely confident in my modifications, I went back to `tokio-line`'s example `echo.rs`. There, I can hit the same `unimplemented!()` by simply adding a newline character at the end of the string sent by the client:

```
$ git checkout c877b8cae8e085f1deb620bcee9958231fff54f1
$ git diff
diff --git a/examples/echo.rs b/examples/echo.rs
index 5372bc4..0b7c840 100644
--- a/examples/echo.rs
+++ b/examples/echo.rs
@@ -35,7 +35,7 @@ pub fn main() {

         // The connect call returns us a ClientHandle that allows us to use the 'Service' as a function
         // - one that returns a future that we can 'await' on.
-        let resp = client.call("Hello".to_string());
+        let resp = client.call("Hello1\n".to_string());
         println!("RESPONSE: {:?}", resp.wait());

         drop(client);
$ cargo run --example echo
   Compiling tokio-line v0.1.0 (file:///Users/nicolas/tokio-line.git)
     Running `target/debug/examples/echo`
GOT: "Hello1"
GOT: ""
thread 'RESPONSE: Ok("Hello1")
<unnamed>' panicked at 'not yet implemented', /Users/nicolas/.cargo/git/checkouts/tokio-proto-c8cedf07823756f8/master/src/proto/pipeline/pipeline.rs:142
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:788
error: Process didn't exit successfully: `target/debug/examples/echo` (exit code: 101)
```

I'm not sure it makes sense to put two frames in a single `call()` in this example, but:
1. `tokio-proto` should be resilient to something like this I think
2. I am working with a single frame in by adaptation of `tokio-line`, both in the initial `client.call()` and the response from the server.

If it can help, adding print logs to `process_out_frame()` from `tokio-proto`'s `src/proto/pipeline/pipeline.rs` shows that it's called twice. It could be that I forgot to clear the `buf` in `framed_transport.rs`'s `parse()` though.

**Comment by nbigaouette** [comment] 2016-08-30 03:01
As suspected, `process_out_frame()` was called twice because I did not removed the read data from the buffer in `parse()`.

While this being required, it did not solve completely the issue. I still sometimes hit the `unimplemeted!()`. I now have three different behaviour:
1. The whole ping-pong succeeds; The client connects to the server and send it's packet/frame. The server receives it, compares the data and report if does not match the expected values. It then replies with a specific packet/frame. The client prints it properly.
2. The server detects the client connection but never receives anything. The client just hangs.
3. Killing the client and restarting it will hit the `unimplemented!()`.

I think I hit the problem if I kill the server with ctrl+c, leaving an opened socket to opened. If I re-launch the server before the OS times-out the socket, the client will hang (I don't get why the server detects the connection though, or why it can start listening at all). Restarting the client will enable the ping-pong, but the client will hit the `unimplemented!()`. Does that make any sense? While I'm probably breaking things by ctrl+c'ing the client and server, can there be extra check to detect a bad state?

Note:
- I'm on OSX
- The server I'm talking about was written in rust and mio (0.5.0), but does not share any code with the client.

**Comment by scooter-dangle** [comment] 2016-09-20 05:46
> <span>2</span>. The server detects the client connection but never receives anything. The client just hangs.

Have also seen this in experimenting with a protocol that used `tokio-line` as a model on OS X. Was not able to reproduce the behavior on Linux, though.

On OS X, it seemed to occur faster when I was sending larger messages to the server from the client. (I increased the size of the `BlockBuf`s initialized to allow larger messages so that I could reproduce it faster.) We chalked it up to being an OS X quirk that won't affect us in production.

**Comment by carllerche** [comment] 2016-09-20 16:20
It's a bit hard for me to follow all the cases described. So, I will provide a quick clarification:

`Service::call` is expected to represent a _single_ request / response exchange. This means that w/ the line protocol, if you do `my_client.call("foo\nbar");` you want to send a request w/ a new line _in_ the request (vs. two separate requests).

The issue is that the line protocol is super simple and including a new line is invalid. I will add a check in the service that returns an error in that case.

That being said, it would be best to not hit any `unimplemented` paths. Unfortunately, I'm not sure which `unimplemented` you are hitting. Could provide more info to help track that down? Either the git revision (the ones listed don't resolve for me) of tokio_proto that hits unimplemented @ line 143 or a repro against current master?

**Comment by carllerche** [comment] 2017-01-05 22:28
I will close this for now.

**Closed as completed by carllerche** 2017-01-05 22:28 UTC
